name: Run R Script

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  # This runs the workflow every minute

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        install.packages(c("lubridate", "tidyverse", "googlesheets4"))

    - name: Run R script
      run: Rscript push.R
      env:
        GDRIVE_PAT: ${{ secrets.GSHEETS_AUTO }}
